module.exports = [
    {
      title: "The Shawshank Redemption",
      shortDescription: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
      image: "https://i.ibb.co/bQDWCPv/sredemp.jpg",
      longDescription: `The Shawshank Redemption is a 1994 American prison drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. The film tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis "Red" Redding (Morgan Freeman), and becomes instrumental in a money laundering operation led by the prison warden Samuel Norton (Bob Gunton). William Sadler, Clancy Brown, Gil Bellows, and James Whitmore appear in supporting roles.
                        Darabont purchased the film rights to King's story in 1987, but development did not begin until five years later, when he wrote the script over an eight-week period. Two weeks after submitting his script to Castle Rock Entertainment, Darabont secured a $25 million budget to produce The Shawshank Redemption, which started pre-production in January 1993. While the film is set in Maine, principal photography took place from June to August 1993 almost entirely in Mansfield, Ohio, with the Ohio State Reformatory serving as the eponymous penitentiary. The project attracted many stars for the role of Andy, including Tom Hanks, Tom Cruise, and Kevin Costner. Thomas Newman provided the film's score.`
    },
    {
      title: "The Godfather",
      shortDescription: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      image: "https://i.ibb.co/wgfSDV5/download.webp",
      longDescription: `The Godfather is a 1972 American epic gangster film[2] directed by Francis Ford Coppola, who co-wrote the screenplay with Mario Puzo, based on Puzo's best-selling 1969 novel of the same title. The film stars an ensemble cast including Marlon Brando, Al Pacino, James Caan, Richard Castellano, Robert Duvall, Sterling Hayden, John Marley, Richard Conte, and Diane Keaton. It is the first installment in The Godfather trilogy, chronicling the Corleone family under patriarch Vito Corleone (Brando) from 1945 to 1955. It focuses on the transformation of his youngest son, Michael Corleone (Pacino), from reluctant family outsider to ruthless mafia boss.
  
      Paramount Pictures obtained the rights to the novel for $80,000, before it gained popularity.[3][4] Studio executives had trouble finding a director; the first few candidates turned down the position before Coppola signed on to direct the film but disagreement followed over casting several characters, in particular, Vito (Marlon Brando) and Michael (Al Pacino). Filming took place primarily on location around New York City and in Sicily, and was completed ahead of schedule. The musical score was composed principally by Nino Rota, with additional pieces by Carmine Coppola.`
    },
    {
      title: "The Dark Knight",
      shortDescription: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      image: "https://i.ibb.co/TqbcbRt/download-1.webp",
      longDescription: `The Dark Knight is a 2008 superhero film directed by Christopher Nolan, from a screenplay co-written with his brother Jonathan. Based on the DC Comics superhero Batman, it is the sequel to Batman Begins (2005), and the second installment in The Dark Knight trilogy. The plot follows the vigilante Batman, police lieutenant James Gordon, and district attorney Harvey Dent, who form an alliance to dismantle organized crime in Gotham City. Their efforts are derailed by the Joker, an anarchistic mastermind who seeks to test how far Batman will go to save the city from chaos. The ensemble cast includes Christian Bale, Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal, and Morgan Freeman.
  
      Warner Bros. Pictures prioritized a sequel following the successful reinvention of the Batman film series with Batman Begins. Christopher and Batman Begins co-writer David S. Goyer developed the story elements, making Dent the central protagonist caught up in the battle between Batman and the Joker. In writing the screenplay, the Nolans were influenced by 1980s Batman comics and crime drama films, and sought to continue Batman Begins' heightened sense of realism. From April to November 2007, filming took place with a $185 million budget in Chicago and Hong Kong, and on sets in England. The Dark Knight was the first major motion picture to be filmed with high-resolution IMAX cameras. Christopher avoided using computer-generated imagery unless necessary, insisting on practical stunts such as flipping an 18-wheel truck and blowing up a factory.`
    },
    {
      title: "The Godfather Part II",
      shortDescription: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
      image: "https://i.ibb.co/HKSh38L/download-2.webp",
      longDescription: `The Godfather Part II is a 1974 American epic crime film. The film is produced and directed by Francis Ford Coppola, loosely based on the 1969 novel The Godfather by Mario Puzo, who co-wrote the screenplay with Coppola. It is both a sequel and a prequel to the 1972 film The Godfather, presenting parallel dramas: one picks up the 1958 story of Michael Corleone (Al Pacino), the new Don of the Corleone family, protecting the family business in the aftermath of an attempt on his life; the prequel covers the journey of his father, Vito Corleone (Robert De Niro), from his Sicilian childhood to the founding of his family enterprise in New York City. The ensemble cast also features Robert Duvall, Diane Keaton, Talia Shire, Morgana King, John Cazale, Mariana Hill, and Lee Strasberg.
  
      Following the success of the first film, Paramount Pictures began developing a follow-up, with many of the cast and crew returning. Coppola, who was given more creative control, had wanted to make both a sequel and a prequel to The Godfather that would tell the story of the rise of Vito and the fall of Michael. Principal photography began in October 1973 and wrapped up in June 1974. The Godfather Part II premiered in New York City on December 12, 1974, and was released in the United States on December 20, 1974, receiving divisive reviews from critics; its reputation, however, improved rapidly, and it soon became the subject of critical re-appraisal. It grossed $48 million in the United States and Canada and up to $93 million worldwide on a $13 million budget. The film was nominated for eleven Academy Awards, and became the first sequel to win Best Picture. Its six Oscar wins also included Best Director for Coppola, Best Supporting Actor for De Niro and Best Adapted Screenplay for Coppola and Puzo. Pacino won Best Actor at the BAFTAs and was nominated at the Oscars.`
    },
    {
      title: "12 Angry Men",
      shortDescription: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
      image: "https://i.ibb.co/Nn9YVLj/download-3.webp",
      longDescription: `12 Angry Men is a 1957 American independent[6][7] legal drama film directed by Sidney Lumet, adapted from a 1954 teleplay of the same name by Reginald Rose.[8][9] The film tells the story of a jury of 12 men as they deliberate the conviction or acquittal of a teenager charged with murder on the basis of reasonable doubt; disagreement and conflict among them force the jurors to question their morals and values. It stars Henry Fonda (who also produced the film with Reginald Rose), Lee J. Cobb, Ed Begley, E. G. Marshall, and Jack Warden.
  
      12 Angry Men received acclaim from critics, despite a lukewarm box office performance. At the 30th Academy Awards, it was nominated for Best Picture, Best Director and Best Screenplay. It is regarded by many as one of the greatest films ever made. In 2007, it was selected for preservation in the United States National Film Registry by the Library of Congress as being "culturally, historically or aesthetically significant".[10] Additionally, it was selected as the second-best courtroom drama ever (after 1962's To Kill a Mockingbird) by the American Film Institute for their AFI's 10 Top 10 list`
    },
    {
      title: "Schindler's List",
      shortDescription: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
      image: "https://i.ibb.co/N7fXs6X/download-4.webp",
      longDescription: `Schindler's List is a 1993 American epic historical drama film directed and produced by Steven Spielberg and written by Steven Zaillian. It is based on the 1982 novel Schindler's Ark by Australian novelist Thomas Keneally. The film follows Oskar Schindler, a German industrialist who saved more than a thousand mostly Polish–Jewish refugees from the Holocaust by employing them in his factories during World War II. It stars Liam Neeson as Schindler, Ralph Fiennes as SS officer Amon Göth, and Ben Kingsley as Schindler's Jewish accountant Itzhak Stern.
  
      Ideas for a film about the Schindlerjuden (Schindler Jews) were proposed as early as 1963. Poldek Pfefferberg, one of the Schindlerjuden, made it his life's mission to tell Schindler's story. Spielberg became interested when executive Sidney Sheinberg sent him a book review of Schindler's Ark. Universal Pictures bought the rights to the novel, but Spielberg, unsure if he was ready to make a film about the Holocaust, tried to pass the project to several directors before deciding to direct it.
      
      Principal photography took place in Kraków, Poland, over 72 days in 1993. Spielberg shot in black and white and approached the film as a documentary. Cinematographer Janusz Kamiński wanted to create a sense of timelessness. John Williams composed the score, and violinist Itzhak Perlman performed the main theme.`
    },
    {
      title: "The Lord of the Rings: The Return of the King",
      shortDescription: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      image: "https://i.ibb.co/kGNwGqV/download-5.webp",
      longDescription: `The Lord of the Rings: The Return of the King is a 2003 epic high fantasy adventure film directed by Peter Jackson from a screenplay by Fran Walsh, Philippa Boyens, and Jackson. It is based on 1955's The Return of the King, the third volume of the novel The Lord of the Rings by J. R. R. Tolkien. The sequel to 2002's The Lord of the Rings: The Two Towers, the film is the third instalment in The Lord of the Rings trilogy. It features an ensemble cast including Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Bernard Hill, Billy Boyd, Dominic Monaghan, Orlando Bloom, Hugo Weaving, Miranda Otto, David Wenham, Karl Urban, John Noble, Andy Serkis, Ian Holm, and Sean Bean. Continuing the plot of the previous film, Frodo, Sam and Gollum make their final way toward Mount Doom to destroy the One Ring, unaware of Gollum's true intentions, while Merry, Pippin, Gandalf, Aragorn, Legolas, Gimli and their allies join forces against Sauron and his legions from Mordor.
  
      The Return of the King was financed and distributed by American studio New Line Cinema, but filmed and edited entirely in Jackson's native New Zealand, concurrently with the other two parts of the trilogy. It premiered on 1 December 2003 at the Embassy Theatre in Wellington and was then released on 17 December 2003 in the US and on 18 December 2003 in New Zealand. The film was acclaimed by both critics and audiences, who considered it to be a landmark in filmmaking and the fantasy film genre, and a satisfying conclusion to the trilogy, with praise for the visual effects, performances, action sequences, direction, screenplay, musical score, costume design, emotional depth, scope, and story. It grossed over $1.1 billion worldwide, becoming the highest-grossing film of 2003 and the second highest-grossing film of all time during its run, as well as the highest-grossing film ever released by New Line Cinema`
    },
    {
      title: "Pulp Fiction",
      shortDescription: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      image: "https://i.ibb.co/wMdKLXf/download-6.webp",
      longDescription: `Pulp Fiction is a 1994 American independent crime film written and directed by Quentin Tarantino from a story he conceived with Roger Avary.[3] It tells four intertwining tales of crime and violence in Los Angeles, California. The film stars John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.
  
      Tarantino wrote Pulp Fiction in 1992 and 1993, incorporating scenes that Avary originally wrote for True Romance (1993). Its plot occurs out of chronological order. The film is also self-referential from its opening moments, beginning with a title card that gives two dictionary definitions of "pulp". Considerable screen time is devoted to monologues and casual conversations with eclectic dialogue revealing each character's perspectives on several subjects, and the film features an ironic combination of humor and strong violence. TriStar Pictures reportedly turned down the script as "too demented". Miramax co-chairman Harvey Weinstein was enthralled, however, and the film became the first that Miramax fully financed.`
    },
    {
      title: "The Lord of the Rings: The Fellowship of the Ring",
      shortDescription: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron",
      image: "https://i.ibb.co/MS296xQ/download-7.webp",
      longDescription: `The Lord of the Rings: The Fellowship of the Ring is a 2001 epic fantasy adventure film directed by Peter Jackson from a screenplay by Fran Walsh, Philippa Boyens, and Jackson, based on 1954's The Fellowship of the Ring, the first volume of the novel The Lord of the Rings by J. R. R. Tolkien. The film is the first installment in The Lord of the Rings trilogy. It features an ensemble cast including Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Billy Boyd, Dominic Monaghan, Orlando Bloom, Christopher Lee, Hugo Weaving, Sean Bean, Ian Holm, and Andy Serkis.
  
      Set in Middle-earth, the story tells of the Dark Lord Sauron, who seeks the One Ring, which contains part of his might, to return to power. The Ring has found its way to the young hobbit Frodo Baggins. The fate of Middle-earth hangs in the balance as Frodo and eight companions (who form the Fellowship of the Ring) begin their perilous journey to Mount Doom in the land of Mordor, the only place where the Ring can be destroyed. The Fellowship of the Ring was financed and distributed by American studio New Line Cinema, but filmed and edited entirely in Jackson's native New Zealand, concurrently with the other two parts of the trilogy.`
    },
    {
      title: "The Good, the Bad and the Ugly",
      shortDescription: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
      image: "https://i.ibb.co/fxt2Wfg/download.jpg",
      longDescription: `The Good, the Bad and the Ugly (Italian: Il buono, il brutto, il cattivo, literally "The good, the ugly, the bad") is a 1966 Italian epic spaghetti Western film directed by Sergio Leone and starring Clint Eastwood as "the Good", Lee Van Cleef as "the Bad", and Eli Wallach as "the Ugly".[9] Its screenplay was written by Age & Scarpelli, Luciano Vincenzoni, and Leone (with additional screenplay material and dialogue provided by an uncredited Sergio Donati),[10] based on a story by Vincenzoni and Leone. Director of photography Tonino Delli Colli was responsible for the film's sweeping widescreen cinematography, and Ennio Morricone composed the film's score, including its main theme. It was an Italian-led production with co-producers in Spain, West Germany, and the United States. Most of the filming took place in Spain.
  
      The film is known for Leone's use of long shots and close-up cinematography, as well as his distinctive use of violence, tension, and highly stylised gunfights. The plot revolves around three gunslingers competing to find a fortune in a buried cache of Confederate gold amid the violent chaos of the American Civil War (specifically the Battle of Glorieta Pass of the New Mexico Campaign in 1862) while participating in many battles, confrontations, and duels along the way.[11] The film was the third collaboration between Leone and Clint Eastwood, and the second with Lee Van Cleef.`
    },
    {
      title: "Forrest Gump",
      shortDescription: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
      image: "https://i.ibb.co/jHc1G6B/download-8.webp",
      longDescription: `Forrest Gump is a 1994 American comedy-drama film directed by Robert Zemeckis and written by Eric Roth. It is an adaptation of the 1986 novel of the same name by Winston Groom and stars Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson, and Sally Field.
  
      The film follows the life of an Alabama man named Forrest Gump (Hanks) and his experiences in the 20th-century United States. Principal photography took place between August and December 1993, mainly in Georgia, North Carolina and South Carolina. Extensive visual effects were used to incorporate Hanks into archived footage and to develop other scenes. The soundtrack features songs reflecting the different periods seen in the film.
      
      Forrest Gump was released in the United States on July 6, 1994, and received widespread critical acclaim for Zemeckis's direction, performances (particularly those of Hanks and Sinise), visual effects, music, and screenplay. The film was a major success at the box office: it became the top-grossing film in the United States released that year and earned over US$678.2 million worldwide during its theatrical run, making it the second-highest-grossing film of 1994, behind The Lion King. The soundtrack sold over 12 million copies. Forrest Gump won six Academy Awards: Best Picture, Best Director, Best Actor for Hanks, Best Adapted Screenplay, Best Visual Effects, and Best Film Editing. It received many award nominations, including Golden Globes, British Academy Film Awards, and Screen Actors Guild Awards.`
    },
    {
      title: "The Lord of the Rings: The Two Towers",
      shortDescription: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.    ",
      image: "https://i.ibb.co/hc0cNFK/download-9.webp",
      longDescription: `The Lord of the Rings: The Two Towers is a 2002 epic high fantasy adventure film directed by Peter Jackson from a screenplay by Fran Walsh, Philippa Boyens, Stephen Sinclair, and Jackson, based on 1954's The Two Towers, the second volume of the novel The Lord of the Rings by J. R. R. Tolkien. The sequel to 2001's The Lord of the Rings: The Fellowship of the Ring, the film is the second instalment in The Lord of the Rings trilogy. It features an ensemble cast including Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Bernard Hill, Christopher Lee, Billy Boyd, Dominic Monaghan, Orlando Bloom, Hugo Weaving, Miranda Otto, David Wenham, Brad Dourif, Karl Urban, and Andy Serkis.
  
      Continuing the plot of the previous film, it intercuts three storylines: Frodo and Sam continue their journey towards Mordor to destroy the One Ring, now aided by Gollum, the ring's untrustworthy former bearer. Merry and Pippin escape their orc captors, meet Treebeard the Ent, and help to plan an attack on Isengard, fortress of Saruman. Aragorn, Legolas, and Gimli, in their pursuit, come to the war-torn nation of Rohan, and are reunited with the resurrected Gandalf before fighting against the legions of the treacherous wizard Saruman at the Battle of Helm's Deep.`
    },
    {
      title: " Fight Club",
      shortDescription: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
      image: "https://i.ibb.co/T8drBX5/download-10.webp",
      longDescription: `Fight Club is a 1999 American film directed by David Fincher, and starring Brad Pitt, Edward Norton and Helena Bonham Carter. It is based on the 1996 novel by Chuck Palahniuk. Norton plays the unnamed narrator, who is discontented with his white-collar job. He forms a "fight club" with soap salesman Tyler Durden (Pitt), and becomes embroiled in a relationship with an impoverished but beguilingly attractive woman, Marla Singer (Bonham Carter).
  
      Palahniuk's novel was optioned by Fox 2000 Pictures producer Laura Ziskin, who hired Jim Uhls to write the film adaptation. Fincher was selected because of his enthusiasm for the story. He developed the script with Uhls and sought screenwriting advice from the cast and others in the film industry. It was filmed in and around Los Angeles from July to December 1998. He and the cast compared the film to Rebel Without a Cause (1955) and The Graduate (1967), with a theme of conflict between Generation X and the value system of advertising.[5][6]`
    },
    {
      title: "Inception",
      shortDescription: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
      image: "https://i.ibb.co/f2TnrTq/download-11.webp",
      longDescription: `Inception is a 2010 science fiction action film[4][5][6] written and directed by Christopher Nolan, who also produced it with Emma Thomas, his wife. The film stars Leonardo DiCaprio as a professional thief who steals information by infiltrating the subconscious of his targets. He is offered a chance to have his criminal history erased as payment for the implantation of another person's idea into a target's subconscious.[7] The ensemble cast includes Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Elliot Page,[a] Tom Hardy, Cillian Murphy, Tom Berenger, Dileep Rao, and Michael Caine.
  
      After the 2002 completion of Insomnia, Nolan presented to Warner Bros. a written 80-page treatment for a horror film envisioning "dream stealers," based on lucid dreaming.[8] Deciding he needed more experience before tackling a production of this magnitude and complexity, Nolan shelved the project and instead worked on 2005's Batman Begins, 2006's The Prestige, and 2008's The Dark Knight.[9] The treatment was revised over six months and was purchased by Warner in February 2009.[10] Inception was filmed in six countries, beginning in Tokyo on June 19 and ending in Canada on November 22.[11] Its official budget was $160 million, split between Warner Bros. and Legendary.[12] Nolan's reputation and success with The Dark Knight helped secure the film's US$100 million in advertising expenditure`
    },
    {
      title: "Star Wars: Episode V - The Empire Strikes Back",
      shortDescription: "After the Rebel Alliance are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
      image: "https://i.ibb.co/yW4gXZx/download-12.webp",
      longDescription: `The Empire Strikes Back (also known as Star Wars: Episode V – The Empire Strikes Back) is a 1980 American epic space opera film directed by Irvin Kershner from a screenplay by Leigh Brackett and Lawrence Kasdan, based on a story by George Lucas. The sequel to Star Wars (1977),[b] it is the second film in the Star Wars film series and the fifth chronological chapter of the "Skywalker Saga". Set three years after the events of Star Wars, the film recounts the battle between the malevolent Galactic Empire, led by the Emperor, and the Rebel Alliance, led by Luke Skywalker and Princess Leia. Hoping to confront the Emperor's powerful disciple, Darth Vader, Luke trains to master the Force. The ensemble cast includes Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, David Prowse, Kenny Baker, Peter Mayhew, and Frank Oz.
  
      Following the success of Star Wars, Lucas hired Brackett to write the sequel. After she died in 1978, he outlined the whole Star Wars saga and wrote the next draft himself, before hiring Raiders of the Lost Ark (1981) writer Kasdan to enhance his work. To avoid the stress he faced directing Star Wars, Lucas handed the responsibility to Kershner and focused on expanding his special effects company Industrial Light & Magic instead. Filmed from March to September 1979 in Finse, Norway, and at Elstree Studios in England, The Empire Strikes Back faced production difficulties, including actor injuries, illnesses, fires, and problems securing additional financing as costs rose. Initially budgeted at $8 million, costs had risen to $30.5 million by the project's conclusion.`
    },
    {
      title: " The Matrix",
      shortDescription: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence",
      image: "https://i.ibb.co/k0Hgzrt/download-13.webp",
      longDescription: `The Matrix is a 1999 science fiction action film[5][6] written and directed by the Wachowskis.[a] It is the first installment in the Matrix film series, starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving and Joe Pantoliano, and depicts a dystopian future in which humanity is unknowingly trapped inside the Matrix, a simulated reality that intelligent machines have created to distract humans while using their bodies as an energy source.[7] When computer programmer Thomas Anderson, under the hacker alias "Neo", uncovers the truth, he joins a rebellion against the machines along with other people who have been freed from the Matrix.
  
      The Matrix is an example of the cyberpunk subgenre of science fiction.[8] The Wachowskis' approach to action scenes was influenced by anime[9] and martial arts films (particularly fight choreographers and wire fu techniques from Hong Kong action cinema); other influences include Plato's cave and 1990s Telnet hacker communities. The film popularized terms such as the red pill, and introduced a visual effect known as "bullet time", in which the heightened perception of certain characters is represented by allowing the action within a shot to progress in slow motion while the camera appears to move through the scene at normal speed, allowing the sped-up movements of certain characters to be perceived normally.`
    },
    {
      title: "Goodfellas",
      shortDescription: "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
      image: "https://i.ibb.co/jw1H9Vx/download-14.webp",
      longDescription: `Goodfellas (stylized GoodFellas) is a 1990 American biographical crime drama film directed by Martin Scorsese, written by Nicholas Pileggi and Scorsese, and produced by Irwin Winkler. It is a film adaptation of the 1985 nonfiction book Wiseguy by Pileggi. Starring Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco and Paul Sorvino, the film narrates the rise and fall of mob associate Henry Hill and his friends and family from 1955 to 1980.
  
      Scorsese initially titled the film Wise Guy and postponed making it; he and Pileggi later changed the title to Goodfellas. To prepare for their roles in the film, De Niro, Pesci and Liotta often spoke with Pileggi, who shared research material left over from writing the book. According to Pesci, improvisation and ad-libbing came out of rehearsals wherein Scorsese gave the actors freedom to do whatever they wanted. The director made transcripts of these sessions, took the lines he liked most and put them into a revised script, which the cast worked from during principal photography.`
    },
    {
      title: "One Flew Over the Cuckoo's Nest",
      shortDescription: "In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse",
      image: "https://i.ibb.co/DMgPXS3/download-15.webp",
      longDescription: `One Flew Over the Cuckoo's Nest is a 1975 American psychological drama film[4] directed by Miloš Forman, based on the stage play One Flew Over the Cuckoo's Nest by Dale Wasserman, in-turned based on the novel of the same name by Ken Kesey. The film stars Jack Nicholson as a new patient at a mental institution, alongside Louise Fletcher as a sadistic nurse. The supporting cast is Will Sampson, Danny DeVito, Sydney Lassick, William Redfield, and the film debuts of Christopher Lloyd and Brad Dourif.
  
      Originally announced in 1962 with Kirk Douglas starring, the film took 13 years to develop.[5] Filming finally began in January 1975 and lasted three months, on location in Salem, Oregon and the surrounding area, and in Depoe Bay on the north Oregon coast. The producers shot the film in the Oregon State Hospital, an actual psychiatric hospital, which is also the setting of the novel. The hospital is in operation, though the original buildings in the film have been demolished. The film was released on November 19, 1975. Considered by many to be one of the greatest films ever made, One Flew Over the Cuckoo's Nest is No. 33 on the American Film Institute's 100 Years... 100 Movies list.`
    },
    {
      title: "Se7en",
      shortDescription: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
      image: "https://i.ibb.co/W6TS561/download-16.webp",
      longDescription: `Seven (often stylized as Se7en)[1] is a 1995 American crime thriller film directed by David Fincher and written by Andrew Kevin Walker. It stars Brad Pitt, Morgan Freeman, Gwyneth Paltrow, and John C. McGinley. Set in an unnamed, crime-ridden city, Seven's narrative follows disenchanted, nearly retired detective William Somerset (Freeman) and his newly transferred partner David Mills (Pitt) as they try to stop a serial killer from executing a series of murders based on the seven deadly sins.
  
      Walker, an aspiring writer, based Seven on his experiences of moving from a suburban setting to New York City during a period of rising crime and drug addiction in the late 1980s. His script was optioned by an Italian film company but, following financial difficulties, the rights were sold to New Line Cinema. Studio executives were opposed to the script's bleak conclusion, insisting on a more mainstream and optimistic outcome. Fincher, determined to re-establish himself after a career setback, was mistakenly sent Walker's original script and, convinced of its merit, committed to directing the project if the original ending remained intact. Principal photography took place in Los Angeles between December 1994 and March 1995, on a $33–$34 million budget.`
    },
    {
      title: "Interstellar",
      shortDescription: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
      image: "https://i.ibb.co/NNfQ9Jg/download-17.webp",
      longDescription: `Interstellar is a 2014 epic science fiction drama film directed by Christopher Nolan, who co-wrote it with his brother Jonathan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine, and Matt Damon. Set in a dystopian future where Earth is suffering from catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.
  
      The screenplay had its origins in a script Jonathan developed in 2007, and was originally set to be directed by Steven Spielberg. Theoretical physicist Kip Thorne was an executive producer and scientific consultant on the film, and wrote the tie-in book The Science of Interstellar. Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Filming began in late 2013 and took place in Alberta, Klaustur, and Los Angeles. Interstellar uses extensive practical and miniature effects, and the company DNEG created additional digital effects.`
    },
    
  
  ];